// Mocks generated by Mockito 5.4.6 from annotations
// in feedz/test/post_feed_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:feedz/domain/entities/postentity/post_entity.dart' as _i5;
import 'package:feedz/domain/repositories/postrepository/post_repository.dart'
    as _i2;
import 'package:feedz/domain/usecases/addcomment/add_comment.dart' as _i7;
import 'package:feedz/domain/usecases/clearcache/clear_cache.dart' as _i9;
import 'package:feedz/domain/usecases/deletecomment/delete_comment.dart' as _i8;
import 'package:feedz/domain/usecases/fetchposts/fetch_posts.dart' as _i3;
import 'package:feedz/domain/usecases/updatelike/update_like.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostRepository_0 extends _i1.SmartFake
    implements _i2.PostRepository {
  _FakePostRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FetchPosts].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchPosts extends _i1.Mock implements _i3.FetchPosts {
  MockFetchPosts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PostRepository);

  @override
  _i4.Future<List<_i5.PostEntity>> call({
    required int? page,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#page: page, #limit: limit}),
            returnValue: _i4.Future<List<_i5.PostEntity>>.value(
              <_i5.PostEntity>[],
            ),
          )
          as _i4.Future<List<_i5.PostEntity>>);
}

/// A class which mocks [ToggleLike].
///
/// See the documentation for Mockito's code generation for more information.
class MockToggleLike extends _i1.Mock implements _i6.ToggleLike {
  MockToggleLike() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PostRepository);

  @override
  _i4.Future<void> call({required int? postId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#postId: postId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AddComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddComment extends _i1.Mock implements _i7.AddComment {
  MockAddComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PostRepository);

  @override
  _i4.Future<void> call({
    required int? postId,
    required String? commentContent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #postId: postId,
              #commentContent: commentContent,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DeleteComment].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteComment extends _i1.Mock implements _i8.DeleteComment {
  MockDeleteComment() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PostRepository);

  @override
  _i4.Future<void> call({required int? postId, required int? commentIndex}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #postId: postId,
              #commentIndex: commentIndex,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ClearCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockClearCache extends _i1.Mock implements _i9.ClearCache {
  MockClearCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePostRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PostRepository);

  @override
  _i4.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
